services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: viper-dashboard
    restart: unless-stopped
    # volumes:
    #   - .:/var/www
    environment:
      - APP_ENV=production
    ports:
      - "8000:80"
